apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: rmq
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitmq-deployment
    spec:
      containers:
        - name: rabbitmq-autocluster
          image: pivotalrabbitmq/rabbitmq-autocluster
          imagePullPolicy: IfNotPresent
          env:
            # For consupmption by rabbitmq-env.conf
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
            - name: ERLANG_COOKIE
              value: "test"
            # - name: RABBITMQ_ERLANG_COOKIE
            #   value: "secret_cookie"
            - name: RABBITMQ_NODENAME
              value: "rabbit@$(MY_POD_IP)"
            - name: AUTOCLUSTER_TYPE
              value: "etcd"
            - name: AUTOCLUSTER_DELAY
              value: "60"
            - name: ETCD_HOST
              value: "etcd"
            - name: AUTOCLUSTER_CLEANUP
              value: "true"
            - name: CLEANUP_WARN_ONLY
              value: "false"
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-deployment
spec:
  selector:
    app: rabbitmq-deployment
  ports:
    - protocol: TCP
      port: 5672
  type: LoadBalancer